/**
 * `snail generate` — turn an OpenAPI document into `@snail-js/api` code.
 *
 * ## Why the command is thin
 *
 * Everything interesting lives in `index.ts` (load → normalise → render) and
 * `writeGenerated`. This module only decides three things a library cannot: which
 * exit code a failure deserves, what the user sees, and whether writing is allowed at
 * all. Keeping that split means the programmatic API and the CLI cannot drift.
 *
 * ## Why an existing non-generated file blocks the run
 *
 * `src/apis/order.api.ts` may be hand-written — perhaps the document never described
 * that endpoint. Silently overwriting it destroys work with no undo, and the file has
 * no marker saying it will be rewritten. Refusing and naming the file makes `--force`
 * an informed decision rather than a reflex.
 */

import { join } from "node:path";
import {
  generateFromOpenAPI,
  hasGeneratedMarker,
  GENERATED_HEADER,
  writeGenerated,
  UsageError,
  DEFAULT_OUT_DIR,
  type GenerateOptions,
  type GenerateResult
} from "../index.js";
import { pathExists } from "../utils/fs.js";
import type { Logger } from "../logger.js";

/**
 * `snail generate` options.
 *
 * Extends the programmatic {@link GenerateOptions} with the CLI-only flags, so the same
 * object can be handed straight to `generateFromOpenAPI` without translation.
 */
export interface GenerateCommandOptions extends GenerateOptions {
  /** List the files that would be written, and write nothing. */
  dryRun?: boolean;
  /** Overwrite files that do not carry the generated header. */
  force?: boolean;
  /** Delete previously generated files below `--out` before writing. */
  clean?: boolean;
  /** Include per-step diagnostics on stderr. */
  verbose?: boolean;
}

/** Paths that exist but were not produced by this tool. */
export function findForeignFiles(
  result: GenerateResult,
  outDir: string
): string[] {
  return result.files
    .map((file) => join(outDir, file.path))
    .filter((target) => pathExists(target) && !hasGeneratedMarker(target, GENERATED_HEADER));
}

/**
 * Run `snail generate`.
 *
 * Throws on failure — `UsageError` for "nothing was attempted", a plain `Error` for
 * "generation failed" — and returns `0` on success. The CLI maps the two to exit codes
 * `2` and `1`; a library caller can do whatever it likes with them.
 */
export async function runGenerate(options: GenerateCommandOptions, logger: Logger): Promise<number> {
  const input = options.input;
  if (input === undefined || input.trim().length === 0) {
    throw new UsageError('missing required option "--input <openapi.json|openapi.yaml>".');
  }

  if (!pathExists(input)) {
    throw new UsageError(`cannot find the OpenAPI document "${input}".`);
  }

  const outDir = options.out && options.out.trim().length > 0 ? options.out : DEFAULT_OUT_DIR;

  logger.debug(`loading ${input}`);
  const result = await generateFromOpenAPI(input, options);

  for (const warning of result.warnings) logger.warn(warning);

  if (options.dryRun === true) {
    logger.out(`dry run: ${result.files.length} file(s) would be written to ${outDir}`);
    for (const file of result.files) logger.out(`  ${join(outDir, file.path)}`);
    return 0;
  }

  const blockers = findForeignFiles(result, outDir);
  if (blockers.length > 0 && options.force !== true) {
    throw new Error(
      `refusing to overwrite ${blockers.length} file(s) that were not generated by @snail-js/cli: ` +
        `${blockers.join(", ")}. Pass --force to overwrite them, or choose another --out directory.`
    );
  }

  const written = await writeGenerated(result, outDir, { clean: options.clean, logger });
  logger.out(`wrote ${written.length} file(s) to ${outDir}`);

  return 0;
}
