/**
 * `snail init` — create the minimal, working service scaffold.
 *
 * ## Why a scaffold and not just `generate`
 *
 * `generate` writes api files that import `../service`, so on a fresh project it
 * produces code that does not compile until `service.ts` exists. `init` is the one
 * command that can be run before anything else, and it deliberately writes the
 * smallest thing that works: a server, a barrel, and a README saying what to do next.
 *
 * ## Why existing files block the run
 *
 * `service.ts` is the file a user is *expected* to edit — adding plugins, interceptors
 * and `@Server` options. Regenerating it without asking would silently drop that work,
 * so the command refuses, names the blocking file, and requires `--force`.
 */

import { join } from "node:path";
import { pathExists, writeTextFile } from "../utils/fs.js";
import { renderServiceFile } from "../emit/service.js";
import { withHeader } from "../emit/format.js";
import type { Logger } from "../logger.js";

/** Where `snail init` writes by default. */
export const DEFAULT_INIT_DIR = "src/service";

/** `baseURL` used when the caller does not pass `--base-url`. */
export const BASE_SERVICE_BASE_URL = "/api";

/** `snail init` options; `force` is the only one that changes what is written. */
export interface InitCommandOptions {
  /** Target directory; defaults to `src/service`. */
  out?: string;
  /** Overwrite existing files. */
  force?: boolean;
  /** `name` passed to `@Server`. */
  name?: string;
  /** `baseURL` passed to `@Server`. */
  baseUrl?: string;
}

/** The barrel `snail init` writes next to `service.ts`. */
export function renderInitBarrel(): string {
  return withHeader('export { service } from "./service";');
}

/**
 * The README `snail init` writes.
 *
 * Deliberately **not** stamped with the generated header: it is meant to be read and
 * edited, and the header is what `snail generate --clean` deletes. A README that
 * vanished on the next clean run would be worse than no README.
 */
export function renderInitReadme(outDir: string): string {
  return `# ${outDir} — @snail-js/api 服务层

这个目录由 \`snail init\` 生成，是项目里唯一创建 \`SnailServer\` 的地方。

## 目录内容

| 文件 | 作用 |
| --- | --- |
| \`service.ts\` | 全局唯一的服务实例。基地址写在 \`@Server({ baseURL })\` 里；要加插件、拦截器、超时，改这里。 |
| \`index.ts\` | 桶文件，对外只暴露 \`service\`。 |

## 下一步

1. 安装运行时依赖：

   \`\`\`bash
   pnpm add @snail-js/api
   \`\`\`

2. 从 OpenAPI 文档生成接口代码。注意 \`--out\` 传的是**源码根目录**，
   生成器会在里面建 \`apis/\`、\`types/\`，并写入 \`service.ts\`、\`index.ts\`：

   \`\`\`bash
   snail generate --input ./openapi.json --out src --clean
   \`\`\`

   想先看看会生成什么，加 \`--dry-run\`；只想生成部分分组，用 \`--tags pet,store\`。

3. 在业务代码里使用（方法调用只是构造请求，\`.send()\` 才真正发出）：

   \`\`\`ts
   import { petApi } from "../index";

   const { data } = await petApi.getPetById(1).send();
   \`\`\`

## 关于版本库

- 生成的文件第一行都是 \`// Generated by @snail-js/cli. Do not edit by hand.\`，
  \`snail generate --clean\` **只会**删除带这一行的文件，手写文件不会被误删。
- 如果不想提交生成物，把 \`apis/\` 和 \`types/\` 加进 \`.gitignore\`；
  \`service.ts\` 是手写入口，建议提交。
`;
}

/**
 * Run `snail init`.
 *
 * Every target is checked before anything is written, so a refusal leaves the
 * directory exactly as it was — a half-initialised project is worse than an
 * untouched one.
 */
export async function runInit(options: InitCommandOptions, logger: Logger): Promise<number> {
  const outDir = options.out && options.out.trim().length > 0 ? options.out : DEFAULT_INIT_DIR;

  const files: Array<{ path: string; contents: string }> = [
    {
      path: join(outDir, "service.ts"),
      contents: renderServiceFile({
        baseUrl: options.baseUrl ?? BASE_SERVICE_BASE_URL,
        name: options.name
      })
    },
    { path: join(outDir, "index.ts"), contents: renderInitBarrel() },
    { path: join(outDir, "README.md"), contents: renderInitReadme(outDir) }
  ];

  const blockers = files.map((file) => file.path).filter((path) => pathExists(path));

  if (blockers.length > 0 && options.force !== true) {
    throw new Error(
      `refusing to overwrite ${blockers.length} existing file(s): ${blockers.join(", ")}. ` +
        "Pass --force to overwrite them."
    );
  }

  for (const file of files) {
    writeTextFile(file.path, file.contents);
    logger.debug(`wrote ${file.path}`);
  }

  logger.out(`initialised ${outDir} with ${files.length} file(s)`);

  return 0;
}
