/**
 * Formatting primitives shared by every emitter.
 *
 * ## Why the generated header lives here
 *
 * The header is not decoration. It is the marker `--clean` uses to decide what may
 * be deleted, and it is the only thing telling a reader of `src/apis/pet.api.ts`
 * that their edit will be overwritten. Both behaviours depend on the *exact* first
 * line, so the constant is defined once and imported by the emitters, the writer and
 * the cleaner.
 *
 * ## Why JSDoc escaping is a helper and not an afterthought
 *
 * A description containing a comment terminator ends the comment early and turns
 * every following line into a syntax error — in a file the user did not write and
 * cannot fix by hand. Escaping is applied by the one function that builds comments,
 * so no emitter can forget it.
 */

/** Exact first line of every generated file; also the `--clean` marker. */
export const GENERATED_HEADER = "// Generated by @snail-js/cli. Do not edit by hand.";

/** One indentation level. Two spaces, matching the repository's `.editorconfig`. */
export const INDENT = "  ";

/** Package the generated api files import their decorators from. */
export const API_PACKAGE = "@snail-js/api";

/** Indent every non-empty line of `text` by `level` levels. */
export function indentBlock(text: string, level: number): string {
  const prefix = INDENT.repeat(level);
  return text
    .split("\n")
    .map((line) => (line.length === 0 ? line : `${prefix}${line}`))
    .join("\n");
}

/**
 * Build a comment from its lines, or `undefined` when there is nothing to say.
 *
 * Returning `undefined` rather than an empty string keeps callers free of
 * "did I already add a blank line?" bookkeeping: `sections` drops empty parts.
 */
export function renderJSDoc(lines: readonly (string | undefined)[], level = 0): string | undefined {
  const body = lines
    .flatMap((line) => (line === undefined ? [] : line.split("\n")))
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    // `*/` inside a description would close the comment; `*\/` reads identically.
    .map((line) => line.replace(/\*\//g, "*\\/"));

  if (body.length === 0) return undefined;

  const prefix = INDENT.repeat(level);
  if (body.length === 1) return `${prefix}/** ${body[0]} */`;

  const inner = body.map((line) => `${prefix} * ${line}`).join("\n");
  return `${prefix}/**\n${inner}\n${prefix} */`;
}

/** Join non-empty blocks with a blank line between them. */
export function sections(blocks: readonly (string | undefined)[]): string {
  return blocks
    .map((block) => (block ?? "").replace(/\s+$/, ""))
    .filter((block) => block.length > 0)
    .join("\n\n");
}

/**
 * Attach a doc comment to the declaration it documents.
 *
 * Uses a single newline, not the blank line `sections` inserts: a comment separated
 * from its declaration by a blank line stops being the declaration's TSDoc, so the
 * IDE hover and the generated docs would lose it.
 */
export function withDocComment(comment: string | undefined, code: string): string {
  return comment === undefined || comment.length === 0 ? code : `${comment}\n${code}`;
}

/** One `import`/`import type` statement's worth of specifiers plus its module. */
export interface ImportSpec {
  /** Named specifiers; rendered sorted so import order never depends on visit order. */
  names: readonly string[];
  /** Module specifier, e.g. `@snail-js/api` or `../types/pet`. */
  from: string;
  /** Emit `import type { … }`, required by `verbatimModuleSyntax`. */
  typeOnly?: boolean;
}

/**
 * Render import statements.
 *
 * `verbatimModuleSyntax` is on in every consumer of this output, so a type-only
 * specifier *must* be marked: `import { Pet }` for an interface is a hard error
 * there, not a style preference.
 */
export function renderImports(specs: readonly ImportSpec[]): string {
  return specs
    .filter((spec) => spec.names.length > 0)
    .map((spec) => {
      const names = [...new Set(spec.names)].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
      const keyword = spec.typeOnly ? "import type" : "import";
      return `${keyword} { ${names.join(", ")} } from ${JSON.stringify(spec.from)};`;
    })
    .join("\n");
}

/**
 * Prepend the generated header.
 *
 * Trailing newline included: every generated file is a text file a human may open,
 * and a missing final newline shows up as a `\ No newline at end of file` diff.
 */
export function withHeader(body: string): string {
  const trimmed = body.replace(/\s+$/, "");
  return trimmed.length === 0 ? `${GENERATED_HEADER}\n` : `${GENERATED_HEADER}\n\n${trimmed}\n`;
}

/** Render a template literal / string literal safely, escaping backslashes. */
export function stringLiteral(value: string): string {
  return JSON.stringify(value);
}
